<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p3dat</string>
		<string>p2dat</string>
		<string>f3dat</string>
		<string>f3fis</string>
		<string>p3fis</string>
		<string>f3prj</string>
		<string>p3prj</string>
		<string>p2prj</string>
	</array>
	<key>name</key>
	<string>Itasca</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\'|\")[a-zA-Z,0-9,_,=,\s,\.,\,,\;,\:,\+,\-,\*,\%,\@,\/,\\,\(,\),\[,\],\{,\}]*(\'|\"))</string>
			<key>name</key>
			<string>string.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(=|\*|\+|\^|\-|\/|\#|\,|\&amp;|\.\.\.|\|)\s*</string>
			<key>name</key>
			<string>keyword.operator.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((;)(?!\{).*$\n?)</string>
			<key>name</key>
			<string>comment.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(&lt;|=&lt;|&gt;|&gt;=|#)\s*</string>
			<key>name</key>
			<string>keyword.operator.comparison.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.p3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.p3dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(define|def|fish define|fish def)\s*([\w+_]+)\s*\(?([a-zA-Z0-9,_,\s*]*)*\)?\s*$\n?</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(call|clean|cy|cyc|cycle|list|load|new|pause|plot|res|restore|rest|ret|return|save|sav|set|solve|step|title)\b</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(range|calm)\b\s+</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.p3dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.p3dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*\b(ball|brick|configure|cmat|contact|data|domain|fish|fix|geometry|his|history|ini|initial|measure|mea|model|program|structure|table|wall|zone)\b\s+(\b(add|apply|assemble|attribute|attr|cmodel|call|condition|configure|create|creep|cycle|default|delete|distribute|export|extent|extra|face|fix|free|generate|gravity|gridpoint|groupbehavior|history|import|initialize|interface|interval|link|list|make|new|pile|prop|property|relax|restore|result|save|scalar|solve|title|tolerance|tol|trace)\b\s*)*(\b(and|assign|attach|contact|create|fix|group|or|property|skin|value)\b\s*)*</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\b(mohr-coulomb|double-yield)\b\s+</string>
			<key>name</key>
			<string>variable.parameter.type.p3dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>model names</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\b(bulk|bulk-maximum|coh|cohesion|dens|density|dil|dila|dilation|fric|multiplier|pois|poisson|pressure-cap|shear|table-pressure-cap|ten|tens|tension|young)\b\s+</string>
			<key>name</key>
			<string>variable.parameter.type.p3dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>model parameter names</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*\b(activate|add|addattribute|age|aratio|all|auto|axis|base|bin|box|callback|calm|cap|center|circle|clear|component-id|condition|cylinder|damp|default|deformability|destroy|displacement|dp_mode|dp_nratio|dp_sratio|emod|end1|end-1|end2|end-2|extent|extra|facet|fish|fishhalt|global|groups|group|height|id|kratio|lin_mode|linear|linearcbond|linearpbond|local|mechanical|mratio|method|model|mult|name|nstep|numbin|numbins|onewall|periodic|plane|plugin|polygon|point|porosity|position|position-x|position-y|position-z|positions|prop|property|random|radius|ratio|reflect|remove|resolution|rgap|rotation|rotation-x|rotation-y|rotation-z|rr_fric|rrlinear|set|size|slot|solve|spin|stiffness-normal|stiffness-shear|stiffness|suppress|timestep|time|type|unbal|vel|velocity|velocity-x|velocity-y|velocity-z|vtol|x-rotation|xspin|xvelocity|xvel|volumefraction|y-rotation|yspin|yvelocity|yvel|zdisp|z-rotation|zspin|zvelocity|zvel)\b\s+</string>
			<key>name</key>
			<string>variable.parameter.type.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(command|end_command|endcommand|continue|end|exit section|exit|if|else if|else|end_if|endif|loop while|loop for|loop foreach|loop|end_loop|endloop|section|end_section|endsection|whilestepping)\b</string>
			<key>name</key>
			<string>keyword.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>storage.type.function.p3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@\w+)\(?\s*([a-zA-Z, _, \s]*)\s*\)?\s*</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FISH functions</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ball|ba|comp|contact|creep|global|gp|interface|mech|measure|struct|wall|zone)\b\.\b(active|add|age|contactmap|create|damp|delete|disp|end1|end2|end2|extra|facetlist|face|facet|find|fix|force|gap|gravity|group|head|id|interface|isprop|link|list|load|mass|model|near|next|node|normal|num|open|out|persist|pile|porosity|pos_x|pos_y|prop|pos_z|pos|pp|radius|real|remove|out|set_damp|shear|strain|stress|time|timestep|to|type|unbal|upper|velocity|vel|vertex|vertexlist|vol|write|x|y|z)\b(\.|\(|\W)*(\b(area|delete|disp|extra|force|gp|group|head|id|length|link|near|next|penetration|pos|total|update|vel|x|y|z)\b)*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(array|file|io|map|math|memory|table|time|string)\b\.\b(abs|acos|and|asin|atan|atan2|build|close|cos|create|degrad|delete|dot|exp|gauss|grand|keys|ln|log|mag|mag2|max|min|next|not|open|or|out|pi|real|remove|round|sgn|sin|size|sqrt|sub|tan|time|to|type|union|unit|value|write)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.\b(age|all|app|component|contactmap|create|disp|extra|facetlist|facet|find|global|gravity|group|keys|live|local|near|normal|num|pointer|porosity|pos|radius|real|shear|string|timestep|unbal|value|velocity|vel|vertex|x|xx|xy|xz|y|yy|yz|z|zz)\b(\.|\(|\W)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|float|gravity|grav|int|map|memory|not|null|or|string|table|true|vector)\b</string>
			<key>name</key>
			<string>storage.type.function.p3dat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constructors</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.p3dat</string>
	<key>uuid</key>
	<string>a4358a63-d396-4e0c-9b3d-f0de59021e43</string>
</dict>
</plist>
