<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p3dat</string>
		<string>p3fis</string>
		<string>p2dat</string>
		<string>dat</string>
		<string>p3prj</string>
		<string>p2prj</string>
	</array>
	<key>name</key>
	<string>Itasca PFC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.p3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.language.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*\b(call|res|restore|rest|save|sav|title)\s+(.+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(clean|cy|cyc|cycle|list|new|pause|ret|return|set|solve)\b</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b()\b\s+((?!\{).*$\n?)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(load)\b\s+</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(range|calm)\b\s+</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(ball|brick|configure|cmat|contact|domain|fish|history|measure|mea|wall)\b\s+(\b(add|apply|assemble|attribute|attr|condition|create|default|delete|distribute|export|extent|extra|fix|free|generate|group|history|import|initialize|list|make|prop|property|result|tolerance|tol|trace)\b\s+)*</string>
			<key>name</key>
			<string>constant.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+\b(activate|addattribute|age|aratio|all|auto|axis|base|bin|box|callback|calm|cap|clear|condition|cylinder|damp|default|deformability|dens|density|destroy|displacement|dp_mode|dp_nratio|dp_sratio|emod|end1|end2|extent|extra|fish|fishhalt|fric|global|groups|group|height|id|kratio|lin_mode|local|mechanical|mratio|method|model|mult|name|nstep|numbins|onewall|periodic|plane|plugin|porosity|prop|property|random|radius|reflect|remove|rgap|rr_fric|rrlinear|size|slot|spin|timestep|time|type|unbal|vel|velocity|vtol|xspin|xvelocity|xvel|volumefraction|yspin|yvelocity|yvel|zdisp|zspin|zvelocity|zvel)\b\s+</string>
			<key>name</key>
			<string>variable.parameter.type.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(command|end_command|endcommand|continue|end|exit|if|else if|else|end_if|endif|loop while|loop for|loop foreach|loop|end_loop|endloop)\b</string>
			<key>name</key>
			<string>keyword.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*&amp;\s*$\n?</string>
			<key>name</key>
			<string>keyword.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(=|\*|\+|\^|\-|\/|\#|\,)\s*</string>
			<key>name</key>
			<string>keyword.operator.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\s*(math|abs|acos|and|asin|atan|atan2|cos|degrad|exp|grand|ln|log)\b</string>
			<key>name</key>
			<string>storage.type.function.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\s*(gauss|mag|max|min|not|or|pi|round|sgn|sin|sqrt|tan|union|random|uniform|vector|xcomp|ycomp|zcomp)\b</string>
			<key>name</key>
			<string>storage.type.function.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((;)(?!\{).*$\n?)</string>
			<key>name</key>
			<string>comment.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(&lt;|=&lt;|&gt;|&gt;=|#)\s*</string>
			<key>name</key>
			<string>keyword.operator.comparison.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\'|\")[a-zA-Z,0-9,_,=,\s,\.,\,/,\-,\%,\;,\@,\(,\,+,\[,\])]*(\'|\"))</string>
			<key>name</key>
			<string>string.language.p3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>storage.type.function.p3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@\w+)\(?\s*([a-zA-Z0-9,\.,_]*)\s*\)?\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.p3dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(define|def)\s*([\w+_]+)\s*\(?([a-zA-Z0-9,_]*)\)?\s*$\n?</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FISH functions</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(array|ball|ba|comp|contact|file|global|io|map|mech|measure|table|string|wall)\b\.\b(active|age|build|close|contactmap|create|damp|delete|disp|end1|end2|extra|facetlist|facet|find|force|gap|gravity|group|isprop|keys|list|mass|normal|num|open|persist|porosity|pos_x|pos_y|prop|pos_z|pos|radius|out|set_damp|shear|size|timestep|to|value|velocity|vel|write|x|y|z)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(int|map|string|table)\b(\.|\(|\W)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.p3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.\b(age|all|app|contactmap|create|disp|facetlist|facet|find|global|gravity|keys|local|normal|num|porosity|pos|radius|real|shear|string|timestep|value|velocity|vel|x|y|z)\b(\.|\(|\W)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>end of FISH functions</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+(gravity|grav|null)\s+</string>
			<key>name</key>
			<string>entity.name.function.p3dat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.p3dat</string>
	<key>uuid</key>
	<string>a4358a63-d396-4e0c-9b3d-f0de59021e43</string>
</dict>
</plist>
